### ISSUE TITLE
getRoles undefined

### ISSUE THREAD

**Issue by NeroMancini** [enniel/adonis-acl#12]
In a 'login' action of UserController, I check the user with:
`await auth.attempt(email, password)`

so I get the user data with:
`const myuser = await User.find(auth.user.id)`

and to get his roles:
`const userRoles = await myuser.getRoles()`

but I obtain an array of 1 elem but it's undefined.
Please can you help me? Thanks in advance.

**Comment by veakey** [comment]
Can you post some snippets ? 

Already tested and when you have no roles nor permissions you get an empty array eg

```
const emptyRoles = []
const emptyPermissions = []
```

By the way, which database are you using ? It's working fine with mongo.
Is your role table is clean ? can you post what's inside ?

Cheers!

**Comment by enniel** [comment]
@NeroMancini You must added roles with slug column.

Function getRoles is alias for that code:
```js
const roles = await this.roles().fetch()
return roles.rows.map(({ slug }) => slug)
```

**Comment by NeroMancini** [comment]
I'm using postgresql. Slug column is filled.
I'm using only users, roles and role_user tables; I no need permissions so I didn't import that tables: I thought was the same.
