### ISSUE TITLE
Always get 403 error for multi roles check

### ISSUE THREAD

**Issue by vinhtq** [enniel/adonis-acl#13]
I have a route like this
```
Route
  .route('/users/:id', 'UserController.update', ['PUT', 'PATCH'])
  .middleware(['auth:jwt', 'is:(administrator || user'])
```
I logged in as `User` role and try to call route I always have 403 error.

I tried to delete role `administrator` on role then I can access the route

Can you show me what did I do wrong?

**Comment by vinhtq** [comment]
I found the issue: `adonis-acl` just read the first role and ignore the rest

For example: 

If I have this role setup: `is:(administrator || user)`

If I am a `user` role then I get 403

If I switch the role: `is:(user || administrator)`

If I am a `user` role then I do not get 403 but administrator

**Comment by enniel** [comment]
@vinhtq You can upload the code sample to github? I was unable to reproduce your error.

**Comment by vinhtq** [comment]
@enniel Here is the link https://www.dropbox.com/s/9218pqf80w3gmqg/acl-demo.zip?dl=0

I dig into the code and seem I find some issue

In the file: `adonis-acl/src/Middlewares/Is.js`
If you print out `args` variable, you will see that it cut out the rest role.

For example: 

In you route config file
```
Route
  .route('/users/:id', 'UserController.update', ['PUT', 'PATCH'])
  .middleware(['auth:jwt', 'is:(administrator || user'])
```

The middleware args will have such a value: `[(administrator ]`. It eliminate the `user` role

**Comment by vinhtq** [comment]
@enniel I just tried but still not working. The problem is I think would combine both sides. The core of middleware parser and your library.

```
let expression = args[0]
if (Array.isArray(expression)) {
   expression = expression[0]
}
```

This code still wrong. 

I just find a way around for this

On the route file: 

```
Route
  .route('/users/:id', 'UserController.update', ['PUT', 'PATCH'])
  .middleware(['auth:jwt', 'is:administrator,user'])
```

And the `Is` middleware function
```
let expression = args[0]
if (Array.isArray(expression)) {
    expression = expression.join(' || ')
}
```

**Comment by enniel** [comment]
@vinhtq I'm tried on your demo app. It worked.

```js
Route
  .group(() => {
    Route
      .post('auth/login', 'AuthController.login')

    /***********************
    **** User routes ****
    ***********************/
    Route
      .get('users', 'UserController.index')
      .middleware(['auth:jwt', 'is:(administrator or user)'])
  })
  .prefix('api/v1')
```

**Comment by vinhtq** [comment]
@enniel Ah yeah, it works! My mistake

**Comment by Atinux** [comment]
@enniel I think you can close this issue :)
