### ISSUE TITLE
Roles and Permission Manangement 

### ISSUE THREAD

**Issue by koficypher** [enniel/adonis-acl#14]
I want to manage the roles and permissions in the application am building. I know of creating roles and permissions via the CLI but what about doing it with the controllers. Am asking because Adonis ACL doesnt create model files to reference in your controllers. Do you have to create Model files that extend the Model files in the adonis/acl folder in the node_modules folder or how do you go about it? Please help

**Comment by enniel** [comment]
Example code:
```js
const Role = use('Role')
const User = use('User')

class RolesController {
   async createRole ({ request }) {
     const { name, slug, description } = request.post()
     const role = new Role()
     role.name = name
     role.slug = slug
     role.description = description
     await role.save()
     return role.toJSON()
   }

   async attachRole ({ request }) {
     const { userId, roleId } = request.post()
     const user = await User.find(userId)
     await user.roles().attach([ roleId ])
     return { result: 'ok' }
   }
}
```

See more in docs https://github.com/enniel/adonis-acl#working-with-roles

**Comment by koficypher** [comment]
Thank you @enniel  That worked perfectly
