### ISSUE TITLE
Error when update permissions or roles with ace

### ISSUE THREAD

**Issue by yariksav** [enniel/adonis-acl#21]
When I update existing permission by ase acl:permission it throw exception 

> Error: Undefined binding(s) detected when compiling UPDATE query: update "permissions" set "updated_at" = ? where "id" = ?

Thats because id is undefigned. 

https://github.com/enniel/adonis-acl/blob/3515dff5b0fbdcf6e4fb62b63681e5ce28c68458/commands/Permission.js#L54-L56

Using model.fill({}) will remove the existing attributes.

https://github.com/adonisjs/adonis-lucid/blob/14bbde7f56aeff739666ea1a93f7c6c80972b581/src/Lucid/Model/Base.js#L289-L302

You have to use **merge** instead:
```
permission.merge({
     name, description
})
```

same issue with roles:
https://github.com/enniel/adonis-acl/blob/3515dff5b0fbdcf6e4fb62b63681e5ce28c68458/commands/Role.js#L56

**Comment by enniel** [comment]
Thanks! Fixed in version 1.1.1.

**Comment by yariksav** [comment]
thank you
