### ISSUE TITLE
Where can I add my roles, and permissions?

### ISSUE THREAD

**Issue by danielsalles** [enniel/adonis-acl#5]
I find that in the documentation there are no explanations about the commands.

```
  acl:permission       Create or update permission
  acl:role             
  acl:setup
```

I would like to understand what parameters are required. And with each new project execution on a new machine I need to run the commands again.

Thank you,

**Comment by enniel** [comment]
acl:setup - this command create migrations for permissions and roles, use this command once after install adonis-acl. You can create permissions and roles in Factory and use in seeds:

```js
Factory.blueprint('Adonis/Acl/Role', (faker, i, data = {}) => {
  data = Object.assign({
    name: 'Administrator' || data.name,
    slug: 'administrator' || data.slug
  }, data)
  return data
})

Factory.blueprint('Adonis/Acl/Permission', (faker, i, data = {}) => {
  data = Object.assign({
    name: 'Create Users' || data.name,
    slug: 'create_users' || data.slug
  }, data)
  return data
})
```
