### ISSUE TITLE
InvalidExpression exception with @adonisjs/auth version 2.0.11

### ISSUE THREAD

**Issue by MartinsZieds** [enniel/adonis-acl#7]
there seems to be an issue with the new `@adonisjs/auth` update

if in my routes i have:
```
Route.get('users/all', 'UserController.showAll').middleware(['auth', 'is:administrator'])
```
and i go to this route, then InvalidExpression exception is thrown:
<img width="945" alt="invalidexpression" src="https://user-images.githubusercontent.com/6589463/35072005-33f69220-fbe3-11e7-93a0-a2bb04995056.png">
the `expression` parameter seems to be an array not a string and that is why it's throwing an error

**Comment by enniel** [comment]
This problem in `@adonisjs/framework` > 4.0.28. I'm fixed this, but bug in `@adonisjs/framework`.
