### ISSUE TITLE
integrate with VueJS

### ISSUE THREAD

**Issue by alphaelf** [enniel/adonis-acl#8]
is there any way to integrate `is`,`can` and `scope` to Vue [Directives](https://vuejs.org/v2/guide/custom-directive.html) ?
e.g.
[Vue Browser ACL](https://github.com/mblarsen/vue-browser-acl) use [Browser ACL](https://github.com/mblarsen/browser-acl)

**Comment by enniel** [comment]
You can use [ACLer](https://github.com/enniel/acler) for using on client.
